services:
    user.search_filter:
      parent: 'api_platform.doctrine.orm.search_filter'
      arguments: [ { id: 'exact', username: 'partial' } ]
      tags: [ 'api_platform.filter' ]

    vinil.search_filter:
      parent: 'api_platform.doctrine.orm.search_filter'
      arguments: [ { id: 'exact', name: 'partial' } ]
      tags: [ 'api_platform.filter' ]

    vinil.date_filter:
      parent: 'api_platform.doctrine.orm.date_filter'
      arguments: [ { createdAt: ~ } ]
      tags: [ 'api_platform.filter' ]

    vinil.artist_filter:
      parent: 'api_platform.doctrine.orm.search_filter'
      arguments: [ { artista.name: 'exact' } ]
      tags: [ 'api_platform.filter' ]
