<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2NhS9tj\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2NhS9tj/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container2NhS9tj.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container2NhS9tj\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container2NhS9tj\App_KernelTestDebugContainer([
    'container.build_hash' => '2NhS9tj',
    'container.build_id' => 'fb94feb2',
    'container.build_time' => 1676976017,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2NhS9tj');
