<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYwN8Swe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYwN8Swe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYwN8Swe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYwN8Swe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYwN8Swe\App_KernelDevDebugContainer([
    'container.build_hash' => 'YwN8Swe',
    'container.build_id' => '57e0b934',
    'container.build_time' => 1676976000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYwN8Swe');
